name: Code style check

on:
  workflow_dispatch:
  pull_request:

jobs:
  job_lint_C:
    name: Lint C code
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: 'src include/'

  job_lint_python:
    name: Lint Python code
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      src_directory: .
      setup_directory: tests/speculos
      req_directory: tests/speculos
